<%@ Page Title="" Language="C#" MasterPageFile="~/Resources/Master-Pages/Site.Master" AutoEventWireup="true" CodeBehind="EmbeddedError.aspx.cs" Inherits="OWASP.WebGoat.NET.EmbeddedError" %>
<script runat="server">
    protected void UpdateMessage(object sender, EventArgs e)
    {
        //lblMessage.Text= "Time is now: " + DateTime.Now.ToString("t");
        int first = int.Parse(txtNumberOne.Text);
        int second = int.Parse(txtNumberTwo.Text);
        int result = 0;
        checked
        {
            result = first + second;
        }
        lblMessage.Text = "Sum of the two integers is " + result.ToString();
    }
</script>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContentPlaceHolder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="BodyContentPlaceholder" runat="server">
    Try to crash this page by adding two numbers: <br />

    <asp:Label ID="Label1" runat="server" Text="First Number:"></asp:Label>

    <asp:TextBox type="text" ID="txtNumberOne" runat="server" name="txtNumberOne" value="0" /> <br />
    <asp:Label ID="Label2" runat="server" Text="Second Number:"></asp:Label>
    <asp:TextBox type="text" ID="txtNumberTwo" runat="server" name="txtNumberTwo" value="0" /> <br />
    <asp:Button ID="addbtn" Text="Add two numbers" runat="server" OnClick="UpdateMessage" /><br />
    <asp:Label ID="lblMessage" runat="server" />
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="HelpContentPlaceholder" runat="server">
    ASP.NET allows for embedding C# code as part of ASPX pages by using the &lt;script runat="server" /&gt; tag. 
    The problem with this is the code now embedded in the page is put into an autogenerated class by the Framework and run with some hints at error handling.
    Your goal for this exercise is to get this page to generate an error for the Attack Lab and then implement a fix for it in the Fix Lab.
</asp:Content>
